# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {G:/Vivado/CPUsingle/CPU one cycle.cache/wt} [current_project]
set_property parent.project_path {G:/Vivado/CPUsingle/CPU one cycle.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/data2Select_32bit.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/data2Select.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/test.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/4dataSelect.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/SW_in.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/seg7.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/clkdiv.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/SignZeroExtend.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/ROM.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/RegFile.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/RAM.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/PC.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/Instruction.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/ControlUnit.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/ALU32.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/LED_top.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/CPU_top.v}
  {G:/Vivado/CPUsingle/CPU one cycle.srcs/sources_1/new/SingleCPU.v}
}
read_xdc {{G:/Vivado/CPUsingle/CPU one cycle.srcs/constrs_1/new/SingleCPU.xdc}}
set_property used_in_implementation false [get_files {{G:/Vivado/CPUsingle/CPU one cycle.srcs/constrs_1/new/SingleCPU.xdc}}]

synth_design -top SingleCPU -part xc7a35tcpg236-1
write_checkpoint -noxdef SingleCPU.dcp
catch { report_utilization -file SingleCPU_utilization_synth.rpt -pb SingleCPU_utilization_synth.pb }
